name: CMake-Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Configure with CMake (Unix Makefiles)
      run: cmake -G "Unix Makefiles" -S build/CMake -B build/CMake

    - name: Build with CMake
      run: cmake --build build/CMake

    - name: Upload Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: MPM-Geomechanics-linux
        path: build/CMake/MPM-Geomechanics
