name: Testing (Linux)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake git

      - name: Clone GoogleTest into external directory
        run: git clone https://github.com/google/googletest.git external/googletest

      - name: Make test build script executable
        run: chmod +x build/testing/cmake-build.bash

      - name: Run build script from testing directory
        run: ./cmake-build.bash
        working-directory: build/testing